Merged PR 17461: Start implementation of structured errors
This sketches out how trident could report errors in a structured form that is both ergonomic and allows them to be nicely serialized to YAML.

The two main files to look at are **src/errors.rs** and **src/lib.rs**.

Example error:
```yaml
message: Failed load local configuration
error: load-local-config
category: initialization
location: src/errors.rs:144
cause: |-
  failed to read file

  Caused by:
      No such file or directory (os error 2)
```

Or if additional metadata is provided with the error:
```yaml
message: Failed to load datastore from '/path/to/datastore.sqlite'
error: !datastore-load
  path: /path/to/datastore.sqlite
category: initialization
location: src/errors.rs:173
cause: |-
  failed to read file

  Caused by:
      No such file or directory (os error 2)
```

The "cause" text block currently just calls into anyhow, but we could implement our own formatting [based on theirs](https://github.com/dtolnay/anyhow/blob/5cad3bf6a2d6198ae29067c9aadf2f0828fdb125/src/fmt.rs#L20C41-L20C41).

---
In order to support incremental conversion of the codebase, this PR introduces two conversion methods:

* `structured()` can be called on an Option or anyhow::Result and produces a `Result<T, TridentError>`
* `unstructured()` does the reverse and converts a structured Result back to an anyhow one.

Related work items: #6145