Merged PR 23699: engineering: failure reports distracting parse failure in py code
# 🔍 Description

A test run failed and added an error to host status which our py test code is failing to parse:

``` yaml
lastError:
  message: Failed to write to datastore
  error: !datastore
    inner: write-to-datastore
  category: servicing
  location: src/datastore.rs:118
  cause: database is locked (code 5)
```

There is currently special handling in the py test code to handle `!image`, change to handle all "!" prefixed yaml.

Related work items: #11787