Merged PR 18732: engineering: Clear host keys during SSH Connection to BM Host to fix HostKey Mismatch errors when booting to runtime OS
# 🔍 Description

What is this PR about? feature/doc/engineering/bug?

Let's take the example of `verity` test case. he host-keys given to the `trident-mos-test-image` when the provisioning OS comes up are as follows :

```
ci-info: no authorized SSH keys fingerprints found for user mariner.
.
.
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZAmfP9FyhvsBzzmYknEr/mJ90QkUut+vDhFZePgSY/ root@trident-mos-testimage
.
.
```

Now the Azure Devops Host is talking to it over the `ed25519 keys` and assumes that the host key being provided is - `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZAmfP9FyhvsBzzmYknEr/mJ90QkUut+vDhFZePgSY/ root@trident-mos-testimage`
and updates it's `known_hosts` file.

When the `trident-verity-testimg` (runtime) is coming up, it goes ahead and changes its host keys to the following -
```
ci-info: no authorized SSH keys fingerprints found for user mariner.
.
.
.
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINFYjKqZNgBUNvdCjgH/6sBInuFlfXeXp2AVsgFrTX8R root@trident-verity-testimg
.
.
```

Now when it comes up, the Azure Devops host is expecting the key ending `+vDhFZePgSY/` but the host is providing its key ending `2AVsgFrTX8R` leading to it throwing up the error -
```
paramiko.ssh_exception.BadHostKeyException: Host key for server '10.8.4.70' does not match: got 'AAAAC3NzaC1lZDI1NTE5AAAAINFYjKqZNgBUNvdCjgH/6sBInuFlfXeXp2AVsgFrTX8R', expected 'AAAAC3NzaC1lZDI1NTE5AAAAIMZAmfP9FyhvsBzzmYknEr/mJ90QkUut+vDhFZePgSY/'
```

Due to this we are clearing paramiko's in memory host keys whenever we get a host key mismatch. This PR achieves that

# 🤔 Rationale

Why is this PR needed?

To get rid of occasional Host Key mismatch errors on BM Pipelines.

# 📝 Checks

- [ ] Check [dev-docs/manual-validation.md](/dev-docs/manual-validation.md)

Pipeline run: https://dev.azure.com/mariner-org/ECF/_build/results?buildId=552177&view=results

# 📌 Follow-ups

TODO:

- #0000

# 🗒️ Notes

----
#### AI description (iteration 1)
#### PR Classification
This pull request is a bug fix, aimed at resolving Host Key Mismatch errors during SSH connections to Bare Metal (BM) Hosts.

#### PR Summary
The changes in this pull request primarily focus on handling `BadHostKeyException` during SSH connections and automatically adding new host keys to prevent Host Key Mismatch errors. The default IP addresses for certain parameters have also been updated.
- In `deploy_on_bm.py`, the `wait_for_ssh_connection` function now catches `BadHostKeyException` and clears the host keys before retrying the connection. The `main` function sets the missing host key policy to `AutoAddPolicy` to automatically add new host keys.
- The default IP addresses for `bmcIp` in `baremetal-deploy.yml`, `oamIp` in `baremetal-testing.yml` and `baremetal-update-trident-host-config.yml` have been updated.
- The `targetStage` parameter in `trident.yml` has been changed from `ci` to `pre`.

Related work items: #7526